#Karen Vanessa Acosta Enciso. 63201022


In [ ]:
!pip install wooldridge
import pandas as pd
import numpy as np
import wooldridge as wd
import statsmodels.api as sm

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 17.5 MB/s eta 0:00:00


In [ ]:
lista=[[2.8,21],
       [3.4,24],
       [3,26],
       [3.5,27],
       [3.6,29],
       [3,25],
       [2.7,25],
       [3.7,30]]

In [ ]:
arr=np.array(lista)

In [ ]:
YLISTA=arr[:,0]
XLISTA=arr[:,1]


In [ ]:
YLISTA


array([2.8, 3.4, 3. , 3.5, 3.6, 3. , 2.7, 3.7])

In [ ]:
XLISTA

array([21., 24., 26., 27., 29., 25., 25., 30.])

In [ ]:
X=np.c_[np.ones(len(XLISTA)),XLISTA]    
X   

array([[ 1., 21.],
       [ 1., 24.],
       [ 1., 26.],
       [ 1., 27.],
       [ 1., 29.],
       [ 1., 25.],
       [ 1., 25.],
       [ 1., 30.]])

In [ ]:
betas=np.linalg.inv (X.T.dot(X)).dot(X.T.dot(YLISTA))
betas= betas.squeeze()
betas

array([0.56813187, 0.1021978 ])

In [ ]:
y_est=(X@betas)
y_est

array([2.71428571, 3.02087912, 3.22527473, 3.32747253, 3.53186813,
       3.12307692, 3.12307692, 3.63406593])

In [ ]:
u_est=YLISTA-y_est
u_est

array([ 0.08571429,  0.37912088, -0.22527473,  0.17252747,  0.06813187,
       -0.12307692, -0.42307692,  0.06593407])

In [ ]:
u_est2=u_est**2
u_est2

array([0.00734694, 0.14373264, 0.0507487 , 0.02976573, 0.00464195,
       0.01514793, 0.17899408, 0.0043473 ])

In [ ]:
betas_u2=np.linalg.inv (X.T.dot(X)).dot(X.T.dot(u_est2))
betas_u2


array([ 0.23764737, -0.00708432])

In [ ]:
yi_est2=(X@betas_u2)
yi_est2

array([0.08887671, 0.06762375, 0.05345512, 0.0463708 , 0.03220217,
       0.06053944, 0.06053944, 0.02511785])

In [ ]:
prom=u_est2.mean()
prom

0.054340659340659334

In [ ]:
SSE=sum((yi_est2-prom)**2)
SSE

0.002854416920574607

In [ ]:
SST=sum((u_est2-prom)**2)
SST

0.03286000906657431

In [ ]:
R2=SSE/SST  ##R^2
R2

0.08686598091898161

In [ ]:
LM=8*R2 ##MULTIPLICADOR DE LAGRANGE
LM

0.6949278473518529

In [ ]:
import scipy.stats as st
CHI= st.chi2(1)

1-CHI.cdf(0.69)

0.40616438071332606

## ES HOMOCEDASTICO AL SER MAYOR QUE EL P-VALOR



